### ISSUE TITLE
Not working with latest build.

### ISSUE THREAD

**Issue by amdad** [tiipiik/OctoberCMS-RoomBooking#11]
Hello,
thanks for the plugin.

Can you fix it?

![aaoctober](https://cloud.githubusercontent.com/assets/10062429/14752600/7c8162ca-08d0-11e6-878b-f3d8097adc93.png)

**Comment by simaoj** [comment]
Same problem here :(

**Comment by tiipiik** [comment]
This has been fixed with the PR #10
