### ISSUE TITLE
Plugin install not visible in db & back-end, only in file system

### ISSUE THREAD

**Issue by dionduodeka** [tiipiik/OctoberCMS-RoomBooking#12]
When I try to install the plugin it becomes visible in my file system (plugins/tiipiik) but nothing happens in the back-end of the CMS. Also nothing has changed in the DB structure. Weird since I do not see any erros when installing the plugin, October even responds with 'install succesfull'.

Before I tried to install it, I installed other plugins with out any troubles:
- RainLab.blog
- RainLab.user
- RainLab.forum

And after I failed to install RoomBooking I installed the following pluings without any complications:
- GoogleAnalytics
- Pages

So I can't understand what's happening here.

Can someone start by explaning me what should happen after installing the plugin? I can image that, when editing a page, I can drag the RoomBooking compontents into my pages? Or should there become a top-menu item visible with "rooms" or "bookings"?

Thanks in advance!!

**Comment by danielbruni** [comment]
As said on the Plugin Page: You have to install the Rainlab.Translate plugin first

**Comment by tiipiik** [comment]
Thanks for your answer @danielbruni ,

@dionduodeka , @zmove, did it solve your issue ?
