### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by kuzsa** [tiipiik/OctoberCMS-RoomBooking#6]
Good evening , I have a mistake in going to the page number. Tell me what the problem is PHP 5.5.9-1ubuntu4.13
![screenshot-dev1 loc 2015-10-09 21-42-08](https://cloud.githubusercontent.com/assets/2987543/10401315/e6fd423a-6ec6-11e5-87d2-e5fa2e6e5752.png)

**Comment by tiipiik** [comment]
Hi,

Sorry for that, and more for this long time response from myself (I did not receive the notification). Did the last updates fix your problem ?

Please let me know.
